name: Build and Publish Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build app
        run: npm run build

      - name: Zip build folder
        run: |
          zip -r react-build.zip dist
        # use "build" instead of "dist" if using CRA

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: react-build.zip